### ISSUE TITLE
Elegir hardware adecuado para Daydream y GoogleVR

### ISSUE THREAD

**Issue by Kiszaner** [Kiszaner/2017_SetasVR_TFG#17]
Hay que mirar las opciones de hardware disponible y compatible con Daydream y GoogleVR, los [teléfonos "Daydream-ready"](https://vr.google.com/intl/es_es/daydream/smartphonevr/phones/), y elegir alguno para el proyecto. Cuanto antes sepa la potencia del dispositivo a utilizar, mejor se podrá optimizar y analizar el rendimiento final del producto.

**Comment by Kiszaner** [comment]
Tras mirar las opciones de teléfonos "Daydream-ready", me decanto por alguno de los siguientes:
- El **_ZTE Axon 7_** pinta muy bien en relación calidad/precio, Snapdragon 820 con 4GB de Ram y 64GB de almacenamiento, estando por [438€ en Fnac](https://www.fnac.es/mp5583626/Telefono-Movil-zte-Axon-7-4g-64gb-oro-Smartphone/w-4). El mejor precio, pero el resto de opciones tienen algo mejor  en sus características que este.
- El **_Pixel de Google_** parece buena opción también, aunque no se hasta que punto el que no lo vendan en España supondrá problemas a la hora de comprarlo o que lo encarezca. Quad-core con placa gráfica Adreno, 4GB de Ram y 32GB de almacenamiento. Por [600€ en Amazon](https://www.amazon.es/Google-Pixel-XL-32-Negro/dp/B01M6ZW7Q8/ref=sr_1_1) desde un vendedor inglés (no se si meterá costes de envío exagerados). **Promete ser la mejor opción por la cantidad de Ram y el chip gráfico dedicado así como por el precio**.
- El **_Huawei Mate pro 9_** es mejor en características y el procesador parece estar diseñado para machine learning, con 6GB de Ram y 128GB de almacenamiento, aunque el precio es algo mayor, [655€ en Fnac](https://www.fnac.es/mp5923401/Huawei-Mate-9-Pro-6gb-Ram-128gb-Rom-Oro/w-4). Me parece la segunda mejor opción por la potencia del procesador y la cantidad de Ram, aunque me echa para atrás el que no tenga un chip gráfico dedicado.
- El **_Asus Zenfone AR_** es sin duda la mejor opción, esta especialmente diseñado para usar Tango (AR) y Daydream (VR), pero su precio lo hace bastante inviable en el presupuesto del proyecto. Por [736€ en lo que creo que es tienda china](https://www.eglobalcentral.com.es/asus-zenfone-ar-zs571kl-dual-sim-4g-128gb-8gb-ram-libre-negro.html), en vendedores como [Amazon el precio no baja de los 1000€](https://www.amazon.es/ZenFone-AR-doble-128GB-Negro/dp/B071K8H883/ref=sr_1_1)

**Comment by joseFranciscoDiez** [comment]
Comprar en Amazon descartado. Lo he intentado y no hacen factura a la fundación.
Probaré con otros modelos, distintos del pixel que tienen mayor distribución
Igualmente también tendré que buscar un headset compatible aunque no sea el de google, si sabes de alguno me comentas,

**Comment by joseFranciscoDiez** [comment]
Merece la pena?
https://www.engadget.com/2018/05/01/oculus-go-launch-date-pricing/
